/**
 * LH Public API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;

import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OperationsApi
 */
public class OperationsApiTest {

    private final OperationsApi api = new OperationsApi();

    
    /**
     * Flight Schedules
     *
     * Scheduled flights between given airports on a given date.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationsSchedulesFromDateTimeByOriginAndDestinationGetTest() throws ApiException {
        String origin = "PAD";
        String destination = "MUC";
        String fromDateTime = "2018-02-24";
        String accept = "application/json";
        Boolean directFlights = null;
        String limit = null;
        String offset = null;
        String response = api.operationsSchedulesFromDateTimeByOriginAndDestinationGet(origin, destination, fromDateTime, accept, directFlights, limit, offset);

        
        assertTrue(response!=null);
        // TODO: test validations
    }
    
}
