/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Link;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Container for meta links.
 */
@ApiModel(description = "Container for meta links.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:51:54.877+02:00")
public class AirportResourceMeta {
  @SerializedName("@Version")
  private String version = null;

  @SerializedName("Link")
  private List<Link> link = null;

  @SerializedName("TotalCount")
  private Integer totalCount = null;

  public AirportResourceMeta version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public AirportResourceMeta link(List<Link> link) {
    this.link = link;
    return this;
  }

  public AirportResourceMeta addLinkItem(Link linkItem) {
    if (this.link == null) {
      this.link = new ArrayList<Link>();
    }
    this.link.add(linkItem);
    return this;
  }

   /**
   * Array: links to resource itself and other related resources.
   * @return link
  **/
  @ApiModelProperty(value = "Array: links to resource itself and other related resources.")
  public List<Link> getLink() {
    return link;
  }

  public void setLink(List<Link> link) {
    this.link = link;
  }

  public AirportResourceMeta totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(value = "")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirportResourceMeta airportResourceMeta = (AirportResourceMeta) o;
    return Objects.equals(this.version, airportResourceMeta.version) &&
        Objects.equals(this.link, airportResourceMeta.link) &&
        Objects.equals(this.totalCount, airportResourceMeta.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, link, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirportResourceMeta {\n");
    
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

