/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AirportResource;
import java.io.IOException;

/**
 * AirportResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:51:54.877+02:00")
public class AirportResponse {
  @SerializedName("AirportResource")
  private AirportResource airportResource = null;

  public AirportResponse airportResource(AirportResource airportResource) {
    this.airportResource = airportResource;
    return this;
  }

   /**
   * Get airportResource
   * @return airportResource
  **/
  @ApiModelProperty(value = "")
  public AirportResource getAirportResource() {
    return airportResource;
  }

  public void setAirportResource(AirportResource airportResource) {
    this.airportResource = airportResource;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirportResponse airportResponse = (AirportResponse) o;
    return Objects.equals(this.airportResource, airportResponse.airportResource);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airportResource);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirportResponse {\n");
    
    sb.append("    airportResource: ").append(toIndentedString(airportResource)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

