/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AirportResourceAirports;
import io.swagger.client.model.AirportResourceMeta;
import java.io.IOException;

/**
 * Root element of airport response.
 */
@ApiModel(description = "Root element of airport response.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:51:54.877+02:00")
public class AirportResource {
  @SerializedName("Airports")
  private AirportResourceAirports airports = null;

  @SerializedName("Meta")
  private AirportResourceMeta meta = null;

  public AirportResource airports(AirportResourceAirports airports) {
    this.airports = airports;
    return this;
  }

   /**
   * Get airports
   * @return airports
  **/
  @ApiModelProperty(value = "")
  public AirportResourceAirports getAirports() {
    return airports;
  }

  public void setAirports(AirportResourceAirports airports) {
    this.airports = airports;
  }

  public AirportResource meta(AirportResourceMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  @ApiModelProperty(value = "")
  public AirportResourceMeta getMeta() {
    return meta;
  }

  public void setMeta(AirportResourceMeta meta) {
    this.meta = meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirportResource airportResource = (AirportResource) o;
    return Objects.equals(this.airports, airportResource.airports) &&
        Objects.equals(this.meta, airportResource.meta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(airports, meta);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirportResource {\n");
    
    sb.append("    airports: ").append(toIndentedString(airports)).append("\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

