/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.Name;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Container for airport names.
 */
@ApiModel(description = "Container for airport names.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:51:54.877+02:00")
public class AirportNames {
  @SerializedName("Name")
  private List<Name> name = null;

  public AirportNames name(List<Name> name) {
    this.name = name;
    return this;
  }

  public AirportNames addNameItem(Name nameItem) {
    if (this.name == null) {
      this.name = new ArrayList<Name>();
    }
    this.name.add(nameItem);
    return this;
  }

   /**
   * Array: language specific full name of airport.
   * @return name
  **/
  @ApiModelProperty(value = "Array: language specific full name of airport.")
  public List<Name> getName() {
    return name;
  }

  public void setName(List<Name> name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AirportNames airportNames = (AirportNames) o;
    return Objects.equals(this.name, airportNames.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AirportNames {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

