/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Container for coordinates.
 */
@ApiModel(description = "Container for coordinates.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-15T18:51:54.877+02:00")
public class Coordinate {
  @SerializedName("Latitude")
  private Float latitude = null;

  @SerializedName("Longitude")
  private Float longitude = null;

  public Coordinate latitude(Float latitude) {
    this.latitude = latitude;
    return this;
  }

   /**
   * Decimal latitude. Range: -90 (South Pole) to +90 (North Pole), e.g. “51.540”.
   * @return latitude
  **/
  @ApiModelProperty(value = "Decimal latitude. Range: -90 (South Pole) to +90 (North Pole), e.g. “51.540”.")
  public Float getLatitude() {
    return latitude;
  }

  public void setLatitude(Float latitude) {
    this.latitude = latitude;
  }

  public Coordinate longitude(Float longitude) {
    this.longitude = longitude;
    return this;
  }

   /**
   * Decimal longitude. Range: -180 (West of Prime Meridian) to +180 (East of Prime Meridian).
   * @return longitude
  **/
  @ApiModelProperty(value = "Decimal longitude. Range: -180 (West of Prime Meridian) to +180 (East of Prime Meridian).")
  public Float getLongitude() {
    return longitude;
  }

  public void setLongitude(Float longitude) {
    this.longitude = longitude;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Coordinate coordinate = (Coordinate) o;
    return Objects.equals(this.latitude, coordinate.latitude) &&
        Objects.equals(this.longitude, coordinate.longitude);
  }

  @Override
  public int hashCode() {
    return Objects.hash(latitude, longitude);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Coordinate {\n");
    
    sb.append("    latitude: ").append(toIndentedString(latitude)).append("\n");
    sb.append("    longitude: ").append(toIndentedString(longitude)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

