/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CargoApi
 */
@Ignore
public class CargoApiTest {

    private final CargoApi api = new CargoApi();

    
    /**
     * Retrieve all flights
     *
     * Retrieve a list of all possible flights (both direct and connecting) between two airports on a given date. Routes are available for today and up to days in the future.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cargoGetRouteFromDateProductCodeByOriginAndDestinationGetTest() throws ApiException {
        String origin = null;
        String destination = null;
        String fromDate = null;
        String productCode = null;
        String accept = null;
        String response = api.cargoGetRouteFromDateProductCodeByOriginAndDestinationGet(origin, destination, fromDate, productCode, accept);

        // TODO: test validations
    }
    
    /**
     * Shipment Tracking
     *
     * With this tracking service you can easily retrieve your shipment or flight status information.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void cargoShipmentTrackingByAWBPrefixAndAWBNumberGetTest() throws ApiException {
        String aWBPrefix = null;
        String aWBNumber = null;
        String accept = null;
        String response = api.cargoShipmentTrackingByAWBPrefixAndAWBNumberGet(aWBPrefix, aWBNumber, accept);

        // TODO: test validations
    }
    
}
