/*
 * LH Public API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OffersApi
 */
@Ignore
public class OffersApiTest {

    private final OffersApi api = new OffersApi();

    
    /**
     * Lounges
     *
     * Lounge information
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void offersLoungesByLocationGetTest() throws ApiException {
        String location = null;
        String accept = null;
        String cabinClass = null;
        String tierCode = null;
        String lang = null;
        String response = api.offersLoungesByLocationGet(location, accept, cabinClass, tierCode, lang);

        // TODO: test validations
    }
    
    /**
     * Seat Maps
     *
     * Cabin layout and seat characteristics.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void offersSeatmapsDestinationDateCabinClassByFlightNumberAndOriginGetTest() throws ApiException {
        String flightNumber = null;
        String origin = null;
        String destination = null;
        String date = null;
        String cabinClass = null;
        String accept = null;
        String response = api.offersSeatmapsDestinationDateCabinClassByFlightNumberAndOriginGet(flightNumber, origin, destination, date, cabinClass, accept);

        // TODO: test validations
    }
    
}
