/**
 * LH Public API
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiClient;
import io.swagger.client.ApiException;
import io.swagger.client.Configuration;
import io.swagger.client.auth.OAuth;

import org.junit.Before;
import org.junit.Test;
import org.schema.Airport;
import org.schema.Flight;

import de.upb.dbis.astro.adapter.Adapter;

import static org.junit.Assert.assertTrue;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * API tests for OperationsApi
 */
public class OperationsApiTest {

    private OperationsApi api;
    @Before
    public void setUp() throws Exception {
    	
        ApiClient defaultClient = Configuration.getDefaultApiClient();
        
        // Configure OAuth2 access token for authorization: auth
        OAuth auth = (OAuth) defaultClient.getAuthentication("auth");
        auth.setAccessToken("YOUR ACCESS TOKEN");//FIXME Set access token

        api = new OperationsApi();
    }
    
    /**
     * Flight Schedules
     *
     * Scheduled flights between given airports on a given date.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationsSchedulesFromDateTimeByOriginAndDestinationGetTest() throws ApiException {
        String origin = "PAD";
        String destination = "MUC";
        String fromDateTime = "2018-03-15";
        String accept = "application/json";
        Boolean directFlights = false;
        String limit = "10";
        String offset = "0";
        String response = api.operationsSchedulesFromDateTimeByOriginAndDestinationGet(origin, destination, fromDateTime, accept, directFlights, limit, offset);
               
        assertTrue(response!=null);
        // TODO: test validations
    }
    
    @Test
    public void operationsSchedulesFromDateTimeByOriginAndDestinationGetTest2() throws ApiException, ParseException {
        

        Airport owls_origin = new Airport();
        owls_origin.setIataCode("PAD");
        
        Airport owls_destination = new Airport();
        owls_destination.setIataCode("MUC");
        
        String testDate = "2018-03-15";
        DateFormat formatter = new SimpleDateFormat("y-M-d");
        Date owls_fromDataTime = formatter.parse(testDate);
        
        
        Adapter adapter = new Adapter();
        Flight response = adapter.operationsSchedulesFromDateTimeByOriginAndDestinationGet(owls_origin, owls_destination, owls_fromDataTime);
        
        System.out.println(response);
        assertTrue(response!=null);
        
    }
    
    
    
}
